// Generated by CoffeeScript 1.9.0
(function() {
  module.exports = function() {
    this.Given(/^I visit Auth App$/, function() {
      return this.driver.get('http://localhost:3000/');
    });
    this.When(/^I enter "([^"]*)", "([^"]*)", "([^"]*)", "([^"]*)"$/, function(fName, lName, email, pass) {
      return this.Widget.find({
        root: '#signup-form'
      }).then((function(_this) {
        return function() {
          _this.Widget.fill({
            selector: '#firstname',
            value: fName
          });
          _this.Widget.fill({
            selector: '#surname',
            value: lName
          });
          _this.Widget.fill({
            selector: '#email',
            value: email
          });
          _this.Widget.fill({
            selector: '#confirmEmail',
            value: email
          });
          return _this.Widget.fill({
            selector: '#signupPassword',
            value: pass
          });
        };
      })(this));
    });
    this.Then(/^I should see "([^"]*)", "([^"]*)", "([^"]*)", "([^"]*)"$/, function(fName, lName, email, pass) {
      this.Widget.getValue({
        selector: '#firstname'
      }).should.eventually.eql(fName);
      this.Widget.getValue({
        selector: '#surname'
      }).should.eventually.eql(lName);
      this.Widget.getValue({
        selector: '#email'
      }).should.eventually.eql(email);
      this.Widget.getValue({
        selector: '#confirmEmail'
      }).should.eventually.eql(email);
      return this.Widget.getValue({
        selector: '#signupPassword'
      }).should.eventually.eql(pass);
    });
    return this.Then(/^I should see feedback for verified inputs$/, function() {
      return this.Widget.click('body').then((function(_this) {
        return function() {
          return _this.Widget.isPresent('#firstname.valid');
        };
      })(this)).should.eventually.eql(true);
    });
  };

}).call(this);
