module.exports =
  CREATE_POST: 'CREATE_POST'
  VIEW_CREATE_POST: 'VIEW_CREATE_POST'
  UPDATE_POST: 'UPDATE_POST'
  DELETE_POST: 'DELETE_POST'
  ACTIVITY_SEEN: 'ACTIVITY_SEEN'
  RECIEVE_POSTS: 'RECIEVE_POSTS'
  RECIEVE_USER: 'RECIEVE_USER'